[package]
name = "sbf2rnx"
version = "0.1.0"
authors = ["Lars NÃ¦sbye Christensen <lars@naesbye.dk"]
edition = "2021"

[dependencies]
clap = { version = "3.2.15", features = ["yaml"] }
rinex = "0.5.0"
thiserror = "1"